export const MUSIC_TRACKS = [
  { id: 0, title: "PURE CALM I", url: "https://dl.aramia.me/blog/calmmusic/music-to-relax-blog/1%20%281%29.mp3" },
  { id: 1, title: "PURE CALM XII", url: "https://dl.aramia.me/blog/calmmusic/music-to-relax-blog/1%20%2812%29.mp3" },
  { id: 2, title: "PURE CALM XIII", url: "https://dl.aramia.me/blog/calmmusic/music-to-relax-blog/1%20%2813%29.mp3" },
  { id: 3, title: "PURE CALM XIV", url: "https://dl.aramia.me/blog/calmmusic/music-to-relax-blog/1%20%2814%29.mp3" },
  { id: 4, title: "PURE CALM XV", url: "https://dl.aramia.me/blog/calmmusic/music-to-relax-blog/1%20%2815%29.mp3" },
  { id: 5, title: "PURE CALM XVI", url: "https://dl.aramia.me/blog/calmmusic/music-to-relax-blog/1%20%2816%29.mp3" },
  { id: 6, title: "PURE CALM XVII", url: "https://dl.aramia.me/blog/calmmusic/music-to-relax-blog/1%20%2817%29.mp3" },
  { id: 7, title: "PURE CALM XVIII", url: "https://dl.aramia.me/blog/calmmusic/music-to-relax-blog/1%20%2818%29.mp3" },
  { id: 8, title: "PURE CALM XIX", url: "https://dl.aramia.me/blog/calmmusic/music-to-relax-blog/1%20%2819%29.mp3" },
  { id: 9, title: "PURE CALM XX", url: "https://dl.aramia.me/blog/calmmusic/music-to-relax-blog/1%20%2820%29.mp3" },
  { id: 10, title: "ZEN GARDEN I", url: "https://dl.aramia.me/blog/calmmusic/meditation-sound1.mp3" },
  { id: 11, title: "ZEN GARDEN II", url: "https://dl.aramia.me/blog/calmmusic/meditation-sound2.mp3" },
  { id: 12, title: "ZEN GARDEN III", url: "https://dl.aramia.me/blog/calmmusic/meditation-sound3.mp3" },
  { id: 13, title: "ZEN GARDEN IV", url: "https://dl.aramia.me/blog/calmmusic/meditation-sound4.mp3" },
  { id: 14, title: "ZEN GARDEN V", url: "https://dl.aramia.me/blog/calmmusic/meditation-sound5.mp3" },
  { id: 15, title: "ZEN GARDEN VI", url: "https://dl.aramia.me/blog/calmmusic/meditation-sound6.mp3" },
  { id: 16, title: "ZEN GARDEN VII", url: "https://dl.aramia.me/blog/calmmusic/meditation-sound7.mp3" },
  { id: 17, title: "ZEN GARDEN VIII", url: "https://dl.aramia.me/blog/calmmusic/meditation-sound8.mp3" },
  { id: 18, title: "ZEN GARDEN IX", url: "https://dl.aramia.me/blog/calmmusic/meditation-sound9.mp3" },
  { id: 19, title: "ZEN GARDEN X", url: "https://dl.aramia.me/blog/calmmusic/meditation-sound10.mp3" },
  { id: 20, title: "ZEN GARDEN XI", url: "https://dl.aramia.me/blog/calmmusic/meditation-sound11.mp3" },
  { id: 21, title: "ZEN GARDEN XII", url: "https://dl.aramia.me/blog/calmmusic/meditation-sound12.mp3" },
  { id: 22, title: "ZEN GARDEN XIII", url: "https://dl.aramia.me/blog/calmmusic/meditation-sound13.mp3" },
  { id: 23, title: "ZEN GARDEN XIV", url: "https://dl.aramia.me/blog/calmmusic/meditation-sound14.mp3" },
  { id: 24, title: "DEEP AMBIENT X", url: "https://dl.aramia.me/blog/calmmusic/10.mp3" },
  { id: 25, title: "LONG JOURNEY", url: "https://dl.aramia.me/blog/long-meditation/long%20meditation%20%281%29.mp3" },
  { id: 26, title: "DEEP AMBIENT IX", url: "https://dl.aramia.me/blog/calmmusic/9.mp3" },
  { id: 27, title: "3D: DEEP WATER", url: "https://dl.aramia.me/blog/calmmusic/3d/De-Piero-Deep-Water.mp3" },
  { id: 28, title: "3D: WALKING ON WATER", url: "https://dl.aramia.me/blog/calmmusic/3d/De-Piero-Walking-On-Water.mp3" },
  { id: 29, title: "3D: NOT AFRAID", url: "https://dl.aramia.me/blog/calmmusic/3d/G-spliff-Not-Afraid.mp3" },
  { id: 30, title: "3D: ESSENCE ITSELF", url: "https://dl.aramia.me/blog/calmmusic/3d/Kesler-Essence-Itself.mp3" },
  { id: 31, title: "3D: NEURAL FLOW", url: "https://dl.aramia.me/blog/calmmusic/3d/Kesler-Flow.mp3" },
  { id: 32, title: "3D: CALM TRACK", url: "https://dl.aramia.me/blog/calmmusic/3d/Another-Calm-Track.mp3" },
  { id: 33, title: "3D: STILLNESS", url: "https://dl.aramia.me/blog/calmmusic/3d/Stillness-Deep-Meditation.mp3" },
  { id: 34, title: "3D: SOFT NATURE", url: "https://dl.aramia.me/blog/calmmusic/3d/Soft-Nature-Ambient.mp3" },
  { id: 35, title: "3D: NATURE RELAX", url: "https://dl.aramia.me/blog/calmmusic/3d/Nature-Sounds-Relax.mp3" },
  { id: 36, title: "3D: PEACEFUL WAVES", url: "https://dl.aramia.me/blog/calmmusic/3d/Peaceful-Wave-Sounds.mp3" },
  { id: 37, title: "3D: FOREST SOUND", url: "https://dl.aramia.me/blog/calmmusic/3d/Forest-Meditation-Sound.mp3" }
] as const;